FROM akirillov/cake-example:child_image_tag_prefix-88c683

LABEL version="beta"

ENV TEST test
ENV TEST2 test2

COPY child2/start-gpu.sh ${CONF_HOME}/start-gpu.sh

RUN echo "10.2" > ${CONF_HOME}/cuda.version
